# Generated by Django 4.1.4 on 2024-05-07 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_appointment_comment_alter_appointment_scheduled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cui', models.CharField(max_length=25)),
                ('professional_id', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clinic.doctor'),
            preserve_default=False,
        ),
    ]
